.TH VMANGLE "1" "June 2008" "Balsa utilities" "User Commands"
.SH NAME
vmangle \- fix Balsa output for Quartus compatibility
.SH SYNOPSIS
.B vmangle
[\-c] \fIinput\-file\fR [\fIoutput\-file\fR]
.SH DESCRIPTION
Puts a QII_ in front of certain Verilog module names, to prevent
Quartus from complaining about conflicts with its built-in library.
.PP
If either the \fIinput-file\fR or the \fIoutput-file\fR argument is
`\-', then standard input or standard output will be used. If
\fIoutput-file\fR is not specified, it defaults to stdout.
.SH OPTIONS
.TP
.B \-h, \-\-help
Print usage information and quit
.TP
.B \-c
Do renaming compatible with the Balsa_QII_LIB.v library. This library
contains a very limited subset of cells, and can cause errors under
some circumstances. Vmangle comes with a compatible but more complete
technology library called QII-example-cells.v which is the default
target. The \-c option overrides this default behavior.
.SH BUGS
While this program will do the job faster and more safely than going
through and manually using the find/replace feature in Quartus for
every error, it's not perfect. It doesn't properly parse the Verilog
syntax, and the heuristics it uses are not perfect. However, it should
work for Balsa output.
.PP
You should probably use the example technology when generating output
from Balsa, as it is the best supported technology and it works
properly.
.SH AUTHOR
Written by Peter Scott, <pjscott@iastate.edu>.
